version: '3.8'
services:
  dev:
    build: .devcontainer/
    command: sh -c "tail -f /dev/null"
    working_dir: /src
    volumes:
      - ./:/src:delegated
      - /src/node_modules
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4200:4200
